### PR TITLE
Owen's Biography

### PR DESCRIPTION
**Pull request by ostephens**
For the first assignment of Round 12

### CODE REVIEW

**Comment by ostephens** [comment]
Hmmm - tried to squash my three commits into one as suggested by @msarahan to @richardtomsett in a (now deleted) PR. @msarahan pointed at http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html and I also found http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

However I've ended up in the same position as I think @richardtomsett did - I now have two additional commits (5 in total) rather than the single one I was aiming at. Can anyone tell me what I've done wrong?

**Comment by msarahan** [comment]
Hi, I can't tell you what you did wrong without knowing exactly what you did.  Here's a step-by-step process of what I did to make edits to my own PR:

this shows your commits.  When it shows just your one, you know you've done things right.  For now, use it to count the number of commits you want to combine into one.
  git log

do the squashing interactively.  5 here is the number of commits you counted.
  git rebase -i HEAD~5

Your console-based text editor should open, and should show (your) 5 commits.  Squashing goes bottom-up.  Change all but the top entry from "pick" to "squash" or simply "s."  Save and quit.

You should now get another text editor view that shows the new commit to be made.  It has all of the commit messages from each commit.  I usually delete all but the first.  Save and quit when ready.

Now your commits have been squashed into one.  Confirm this with:
  git log

If that looks good, time to push to github.  We need to force the push, because you're rewriting your history
  git push origin +gh-pages

If this doesn't work for you, please post back with the commands that you're trying, and the results you see.

**Comment by ostephens** [comment]
So previously (when I had three commits) I did the following:

git rebase -i HEAD~3
git push origin +gh_pages

At this point I got an error - I'm afraid I don't have a record of it, but it wouldn't let me push updates to github without first pulling the remote branch. Once I'd done this I then was able to push with:

git push origin gh_pages

I guess this is where it went wrong - as instead of overwriting history on the remote repo I brought down that history and then added two further commits?

However, now I'm at this stage I think I don't want to rebase again - as this looks like it would muck up history too far - if I do:

git rebase -i HEAD~5

now I see a load of commits that are from the upstream repo - I don't want to rebase:

pick 3dbdba3 Writeup on first meeting
pick 3bbf6dc Fixed the README so that it points to the correct baseurl. Fixed the navigation so that the TEACHING SOFTWARE CARPENTRY home link isn't broken (added a /)
pick 54653fb Re-fixed the README so that it is the correct URL
pick 13542e8 Adding one more note
pick 7a959bd Added biography for Owen Stephens
pick dfc14c3 Added biography for Owen Stephens
pick 61e20d6 Added blog URL
pick 5d7dc4b Punctuation

I think I'm going to leave it here - this has taught be a couple of things I didn't know, and I don't need to unpick this particularly except for tidiness. As soon as this PR is merged I won't want to be re-writing history so not that much time to fix it :)

**Comment by msarahan** [comment]
Sorry, your error is my fault - gh_pages should be gh-pages (dash instead of underscore.  Too much python has made me dash-averse.

If git log is "correct" with just your one commit, just retry the push with the correct destination (+gh-pages).  Otherwise, here's how I've fixed this in the past (almost certainly not the nicest way, and I'd be happy to learn a better way):
- delete local repository (make sure everything is pushed to GitHub!!)
- re-clone
- re-squash
- re-push

I had issues like this with a long-running PR to an open source project, where I wanted to pull in more recent work from upstream.  If you do this at any point, you'll end up with this same problem: other people's commits in your rebase.  The solution for me was to pull in the upstream updates using

git pull --rebase

instead of 

git pull

This cleanly separated my work from the upstream history.

**Comment by msarahan** [comment]
PS: it looks like 5 might just be the wrong count.  I don't understand why 
git rebase -i HEAD~5 shows so many commits, but does 4 work and show only your stuff?

**Pull request merged**
