### PR TITLE
Adding Phil R's MCQs to blog

### PR DESCRIPTION
**Pull request by philrosenfield**

### CODE REVIEW

**Comment by snim2** [comment]
I believe you have an error in the Python code here. I think:

``` python
 def compute_slope(y=0, x, b=0):
    """calculate the slope, m, in the equation y = mx + b"""
    m = (y - b) / x
    return m
```

Should be:

``` python
 def compute_slope(x, y=0, b=0):
    """calculate the slope, m, in the equation y = mx + b"""
    m = (y - b) / x
    return m
```

as the "default" arguments always have to come last in the parameter list.

**Comment by philrosenfield** [comment]
That's intentional... my first MCQ is aimed to have the student debug that function.

**Comment by snim2** [comment]
Gah! Sorry, should have read right to the end :(

**Comment by philrosenfield** [comment]
:) no worries -- I had it after the question but couldn't figure out how to format markdown with nested lists and a code block in between.

**Pull request merged**
