### PR TITLE
Add biography information for Richard Tomsett

### PR DESCRIPTION
**Pull request by richardtomsett**
Added Richard Tomsett's biography information

### CODE REVIEW

**Comment by msarahan** [comment]
This works too, but the downside for OSS projects is that you lose the comment trail that may be earlier in the other PR.

**Comment by richardtomsett** [comment]
True. I'm not used to this "working with other people" thing ;)

**Comment by gvwilson** [comment]
Hi @richardtomsett,
In order to be stitched into the blog correctly, pages need to have a header with the date/time of publication, the author's name, etc. - please have a look at `2015-02-01-about-greg-wilson.md` for an example.  If you update your file and push back to your own branch, this PR will automatically update.
Thanks,
Greg

**Comment by richardtomsett** [comment]
Hi Greg, sorry about that, I've added the relevant header info and I think it should be displaying correctly now. I think this PR has also updated correctly...
Richard

**Comment by gvwilson** [comment]
Hi Richard,
No need to apologize - Git and GitHub have a very steep learning curve...
Cheers,
Greg

On 2015-02-09 10:20 AM, Richard wrote:

> Hi Greg, sorry about that, I've added the relevant header info and I 
> think it should be displaying correctly now. I think this PR has also 
> updated correctly...
> Richard
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/training-course/pull/27#issuecomment-73525800.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Pull request merged**
