### PR TITLE
About Sarah

### PR DESCRIPTION
**Pull request by ghost**
Adding my bio

### CODE REVIEW

**Comment by gvwilson** [comment]
Hi @linuxchiq,
In order to be stitched into the blog, your post needs to have a header that specifies the author, the publication date, the title, and some tags. Please have a look at some of the other files in _submissions/round-12/0 for examples, and mail me if you have any questions.
Thanks,
@gvwilson

**Comment by ghost** [comment]
Do I have to submit a new pull request or this one has the change?

**Comment by gvwilson** [comment]
Hi Sarah,

If you change your file and push to your repository, the pull request 
will update automatically - it always compares the most recent version 
of the source repository (yours) with the current version of the 
destination repository (swcarpentry's).

Thanks,
Greg

**Comment by gvwilson** [comment]
Thanks very much - I've added a question to your file and pushed back to this repository. To get it and answer the question, please do the following:
1. On your desktop, add this repository as a remote called "upstream" using `git add upstream https://github.com/swcarpentry/training-course.git`
2.  Download the most recent changes in this repository to your desktop using `git pull upstream gh-pages`.
3. Edit your file to answer the question I've added to it.
4. Create a new pull request by pushing to _your_ repository on GitHub with `git push origin gh-pages` and then pushing the "create a PR" button.

Please let me know how it goes.

Thanks,
@gvwilson

**Pull request merged**
