### PR TITLE
MCQ

### PR DESCRIPTION
**Pull request by ocefpaf**
I apologize for my tardiness and hope there is still time!

### CODE REVIEW

**Comment by ocefpaf** [comment]
@gvwilson is it to late to get this merged?

**Comment by gvwilson** [comment]
I think so.

**Comment by gvwilson** [comment]
The deadline for this was several days ago, so I'm closing this one.

**Comment by ocefpaf** [comment]
OK.  Should I keep following the meetings?

**Comment by gvwilson** [comment]
HI Filipe,
Yes, please keep attending.
Thakns,
Greg

On 2015-03-17 2:09 PM, Filipe wrote:

> OK. Should I keep following the meetings?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/training-course/pull/366#issuecomment-82576535.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Pull request closed without merging**
