### PR TITLE
Add a question to each biography.

### PR DESCRIPTION
**Pull request by gvwilson**
This gives people practice merging changes into their own repositories, and also prompts them to think about the differences between how newcomers see things and how experienced users remember things.

### CODE REVIEW

**Comment by sstevens2** [comment]
Just curious, why do some of the files look like only the question was added(example, mine) where others show that the paragraph was deleted and added back in exactly the same with the question below it(example, 2015-02-05-about-amy-boyle.md)?

**Comment by msarahan** [comment]
Amy's file looks like it had 2 things to cause this: all text on only one line, and no line break at the end of the file.  Greg adding one line break at the end of her line made the whole paragraph look changed. 

Editors handle line wrap differently. Some add line breaks for you, while others only visually wrap the line without adding like breaks.  In general, adding line breaks is nicer for working with source code and collaboratively editing.  You point out a great example here of why that is nicer.

**Comment by sstevens2** [comment]
Thanks Mike!  I had added line breaks intentionally to my bio after seeing some comments on pull requests but it is great to see an example of where that is useful.

**Comment by burkesquires** [comment]
Hi Greg,

A question of clarification...when you ask us to "Add a question to each
biography" are you asking for "each of us" to ad a question to our
respective branch / pull request or are you asking for us to add a question
to "each branch / pull request"? I think it is the former.

Cheers,

Burke Squires

On Wed, Feb 11, 2015 at 7:41 AM, Greg Wilson notifications@github.com
wrote:

> This gives people practice merging changes into their own repositories,
> and also prompts them to think about the differences between how newcomers
> 
> ## see things and how experienced users remember things.
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/swcarpentry/training-course/pull/80
> Commit Summary
> - Add a question to each biography.
> 
> File Changes
> - _M_ _submissions/round-12/0/2015-02-01-about-avijit-bandyopadhyay.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-0
>   (2)
> - _M_ _submissions/round-12/0/2015-02-01-about-greg-wilson.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-1
>   (9)
> - _M_ _submissions/round-12/0/2015-02-01-about-wil-cornwell.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-2
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-adam-richie-halford.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-3
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-amy-boyle.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-4
>   (4)
> - _M_ _submissions/round-12/0/2015-02-05-about-auriel-fournier.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-5
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-ben-weinstein.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-6
>   (1)
> - _M_ _submissions/round-12/0/2015-02-05-about-burke-squires.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-7
>   (2)
> - _M_ _submissions/round-12/0/2015-02-05-about-catherine-devlin.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-8
>   (2)
> - _M_ _submissions/round-12/0/2015-02-05-about-darya-vanichkina.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-9
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-dirk-eddelbuettel.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-10
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-karl-broman.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-11
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-michael-sarahan.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-12
>   (2)
> - _M_ _submissions/round-12/0/2015-02-05-about-owen-stephens.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-13
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-phil-rosenfield.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-14
>   (2)
> - _M_ _submissions/round-12/0/2015-02-05-about-remi-daigle.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-15
>   (4)
> - _M_ _submissions/round-12/0/2015-02-05-about-sarah-mount.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-16
>   (3)
> - _M_ _submissions/round-12/0/2015-02-05-about-simon-fraser.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-17
>   (1)
> - _M_ _submissions/round-12/0/2015-02-05-martin-bentley.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-18
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-belinda-weaver.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-19
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-daniel-wheeler.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-20
>   (3)
> - _M_ _submissions/round-12/0/2015-02-06-about-evgenij-belikov.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-21
>   (3)
> - _M_ _submissions/round-12/0/2015-02-06-about-filipe_fernandes.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-22
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-fran-navarro-brull.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-23
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-hugues-fontenelle.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-24
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-john-pormann.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-25
>   (3)
> - _M_ _submissions/round-12/0/2015-02-06-about-jon-borrelli.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-26
>   (3)
> - _M_ _submissions/round-12/0/2015-02-06-about-joseph-long.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-27
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-konrad-foerstner.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-28
>   (4)
> - _M_ _submissions/round-12/0/2015-02-06-about-kyler-brown.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-29
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-laura-graham.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-30
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-malvika-sharan.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-31
>   (3)
> - _M_ _submissions/round-12/0/2015-02-06-about-pawel-pomorski.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-32
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-richard-tomsett.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-33
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-sue-mcclatchy.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-34
>   (2)
> - _M_ _submissions/round-12/0/2015-02-06-about-victor-kwangchun-lee.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-35
>   (1)
> - _M_ _submissions/round-12/0/2015-02-06-about-zakariyya-mughal.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-36
>   (2)
> - _M_ _submissions/round-12/0/2015-02-07-about-javier-garcia.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-37
>   (2)
> - _M_ _submissions/round-12/0/2015-02-08-about-luke-johnston.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-38
>   (2)
> - _M_ _submissions/round-12/0/2015-02-08-about-marios-isaakidis.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-39
>   (4)
> - _M_ _submissions/round-12/0/2015-02-08-about-matthew-bourque.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-40
>   (4)
> - _M_ _submissions/round-12/0/2015-02-08-about-richard-kip.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-41
>   (2)
> - _M_ _submissions/round-12/0/2015-02-09-about-alex-wiltschko.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-42
>   (2)
> - _M_ _submissions/round-12/0/2015-02-09-about-arliss-collins.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-43
>   (2)
> - _M_ _submissions/round-12/0/2015-02-09-about-johan-hjelm.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-44
>   (2)
> - _M_ _submissions/round-12/0/2015-02-09-about-john-constable.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-45
>   (2)
> - _M_ _submissions/round-12/0/2015-02-09-about-kathy-chung.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-46
>   (3)
> - _M_ _submissions/round-12/0/2015-02-09-about-kim-moir.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-47
>   (2)
> - _M_ _submissions/round-12/0/2015-02-09-about-peter-fields.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-48
>   (2)
> - _M_ _submissions/round-12/0/2015-02-09-about-rachel-glover.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-49
>   (4)
> - _M_ _submissions/round-12/0/2015-02-10-about-alistair-walsh.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-50
>   (2)
> - _M_ _submissions/round-12/0/2015-02-10-about-derek-howard.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-51
>   (4)
> - _M_ _submissions/round-12/0/2015-02-10-about-eli-draizen.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-52
>   (2)
> - _M_ _submissions/round-12/0/2015-02-10-about-narayanan-raghupathy.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-53
>   (2)
> - _M_ _submissions/round-12/0/2015-02-10-about-pandurang-kolekar.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-54
>   (2)
> - _M_ _submissions/round-12/0/2015-02-10-about-sarah-stevens.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-55
>   (2)
> - _M_ _submissions/round-12/0/2015-02-10-about-vladimir-sudilovsky.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-56
>   (4)
> - _M_ _submissions/round-12/0/2015-02-11-about-laurie-baker.md
>   https://github.com/swcarpentry/training-course/pull/80/files#diff-57
>   (1)
> 
> Patch Links:
> - https://github.com/swcarpentry/training-course/pull/80.patch
> - https://github.com/swcarpentry/training-course/pull/80.diff
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swcarpentry/training-course/pull/80.

## 

"We hold these truths to be self-evident, that all men are created equal,
that they are endowed by their creator with certain inalienable Rights,
that among these are Life, Liberty and the pursuit of Happiness." United
States Declaration of Independence

---

Burke Squires
burkesquires AT gmail.com

**Comment by gvwilson** [comment]
Hi Burke,

You're correct - I'd like each person to add that question and its 
answer to their own biography.

Thans ,
Greg

On 2015-02-13 5:13 PM, R. Burke Squires wrote:

> Hi Greg,
> 
> A question of clarification...when you ask us to "Add a question to each
> biography" are you asking for "each of us" to ad a question to our
> respective branch / pull request or are you asking for us to add a 
> question
> to "each branch / pull request"? I think it is the former.
> 
> Cheers,
> 
> Burke Squires
> 
> On Wed, Feb 11, 2015 at 7:41 AM, Greg Wilson notifications@github.com
> wrote:
> 
> > This gives people practice merging changes into their own repositories,
> > and also prompts them to think about the differences between how 
> > newcomers
> > 
> > ## see things and how experienced users remember things.
> > 
> > You can view, comment on, or merge this pull request online at:
> > 
> > https://github.com/swcarpentry/training-course/pull/80
> > Commit Summary
> > - Add a question to each biography.
> > 
> > File Changes
> > - _M_ _submissions/round-12/0/2015-02-01-about-avijit-bandyopadhyay.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-0
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-01-about-greg-wilson.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-1
> >   (9)
> > - _M_ _submissions/round-12/0/2015-02-01-about-wil-cornwell.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-2
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-adam-richie-halford.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-3
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-amy-boyle.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-4
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-05-about-auriel-fournier.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-5
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-ben-weinstein.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-6
> >   (1)
> > - _M_ _submissions/round-12/0/2015-02-05-about-burke-squires.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-7
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-05-about-catherine-devlin.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-8
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-05-about-darya-vanichkina.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-9
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-dirk-eddelbuettel.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-10
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-karl-broman.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-11
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-michael-sarahan.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-12
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-05-about-owen-stephens.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-13
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-phil-rosenfield.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-14
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-05-about-remi-daigle.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-15
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-05-about-sarah-mount.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-16
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-05-about-simon-fraser.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-17
> >   (1)
> > - _M_ _submissions/round-12/0/2015-02-05-martin-bentley.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-18
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-belinda-weaver.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-19
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-daniel-wheeler.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-20
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-06-about-evgenij-belikov.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-21
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-06-about-filipe_fernandes.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-22
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-fran-navarro-brull.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-23
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-hugues-fontenelle.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-24
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-john-pormann.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-25
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-06-about-jon-borrelli.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-26
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-06-about-joseph-long.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-27
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-konrad-foerstner.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-28
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-06-about-kyler-brown.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-29
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-laura-graham.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-30
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-malvika-sharan.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-31
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-06-about-pawel-pomorski.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-32
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-richard-tomsett.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-33
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-sue-mcclatchy.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-34
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-06-about-victor-kwangchun-lee.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-35
> >   (1)
> > - _M_ _submissions/round-12/0/2015-02-06-about-zakariyya-mughal.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-36
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-07-about-javier-garcia.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-37
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-08-about-luke-johnston.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-38
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-08-about-marios-isaakidis.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-39
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-08-about-matthew-bourque.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-40
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-08-about-richard-kip.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-41
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-09-about-alex-wiltschko.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-42
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-09-about-arliss-collins.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-43
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-09-about-johan-hjelm.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-44
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-09-about-john-constable.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-45
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-09-about-kathy-chung.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-46
> >   (3)
> > - _M_ _submissions/round-12/0/2015-02-09-about-kim-moir.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-47
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-09-about-peter-fields.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-48
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-09-about-rachel-glover.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-49
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-10-about-alistair-walsh.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-50
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-10-about-derek-howard.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-51
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-10-about-eli-draizen.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-52
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-10-about-narayanan-raghupathy.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-53
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-10-about-pandurang-kolekar.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-54
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-10-about-sarah-stevens.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-55
> >   (2)
> > - _M_ _submissions/round-12/0/2015-02-10-about-vladimir-sudilovsky.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-56
> >   (4)
> > - _M_ _submissions/round-12/0/2015-02-11-about-laurie-baker.md
> >   https://github.com/swcarpentry/training-course/pull/80/files#diff-57
> >   (1)
> > 
> > Patch Links:
> > - https://github.com/swcarpentry/training-course/pull/80.patch
> > - https://github.com/swcarpentry/training-course/pull/80.diff
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/swcarpentry/training-course/pull/80.
> 
> ## 
> 
> "We hold these truths to be self-evident, that all men are created equal,
> that they are endowed by their creator with certain inalienable Rights,
> that among these are Life, Liberty and the pursuit of Happiness." United
> States Declaration of Independence
> 
> ---
> 
> Burke Squires
> burkesquires AT gmail.com
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/training-course/pull/80#issuecomment-74336478.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Pull request merged**
