### PR TITLE
Talkpage

### PR DESCRIPTION
**Pull request by mtb-za**
Made some additional notes on the talkpage.

Added a useful interactive tutorial for markdown, a good primer for basic git, a much more complete git reference (which includes a section on github), and a note about Jekyll, with a couple of links to how it uses file structure and how to format the YAML frontmatter.

### CODE REVIEW

**Comment by wking** [comment]
On Thu, Apr 02, 2015 at 03:30:00PM -0700, Martin Bentley wrote:

> … a good primer for basic git, a much more complete git reference
> (which includes a section on github)…

I like both of these references.  If you're collecting links to
external tutorials, [1](https://try.github.io/) is also nice.  And our Science Lab friends
point [2](https://github.com/mozillascience/studyGroupLessons#check-out-our-friends) here [3](although I haven't looked that one over in
detail).

The rest of these changes look good to me.

**Comment by mtb-za** [comment]
Oooo.... That first one is nice. I usually just reach for Pro Git, but that might not be the most accessible if one is just trying to grasp the basics. That seems to do it nicely.

Have added that and git-it, as well as [this comment](https://github.com/swcarpentry/training-course/issues/445#issuecomment-89140339).

**Comment by wking** [comment]
I added a few comments on ef530d7ad.  The after fixing the
capitalization issues and dropping the “Please do this on your own
fork…” sentence, this PR looks good to me.

I checked out another SWC repository where I have push access but no
existing fork, and I do see a “Create a new file here” button (not a
“Fork this project and create a new file” button).  I expect GitHub
will create a _-patch-_ branch in the swcarpentry repository in that
case (but I haven't tested this).  This is probably what happened here
[1](https://github.com/swcarpentry/shell-novice/issues/66#issuecomment-83082738), and that seems fine.  Personally, I'd avoid granting trainee's
access, but I've always preferred [2](http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#Integration-Manager-Workflow) to [3](http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#Centralized-Workflow).  So far, SWC seems to
prefer [3](or at least, more permissive push access to the central
repositories than [2]).

**Comment by mtb-za** [comment]
As far as I can tell, we do have permission to edit the main repo, as part of the Software Carpentry organisation. @gvwilson can you confirm if I need to leave

> Please do this on your own fork, so that Greg can review incoming changes.

 in or not? As far as I can tell, I have the required permissions to edit the file in place, although there is an option for creating a branch rather than committing directly: 

github_crop2

github_crop1

github_crop

So I assume that we want to encourage a branch and PR?

I have fixed the capitalisation issues though, and will update this PR as soon as I get clarification on the above.

**Comment by wking** [comment]
On Fri, Apr 03, 2015 at 11:32:42AM -0700, Martin Bentley wrote:

> As far as I can tell, we do have permission to edit the main repo,
> as part of the Software Carpentry organisation…

Thanks for doing the legwork here and with your screenshots.  If we
decide to keep trainee push access to the central repository, I'd
suggest having them edit the central repository but chose the “Create
a new branch…” radio button after editing the file.  That way you
don't have to explain about forks (and there's really no reason to
fork if you're sharing push access to a central repository).  But it's
not _that_ hard to explain forks, so I'm ok if folks would rather go
that way to put a bit more space between new-to-Git trainees and the
central repository.  And once you start suggesting folks work in their
own forks, you're using [1](http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#Integration-Manager-Workflow), and you might as well revoke trainee push
access to the central repository.

**Comment by mtb-za** [comment]
Yeah. I reckon that it makes sense to use the web-interface as far as possible, if it is simpler than the CLI. I am not a good judge of that though, since I am pretty comfortable using a CLI, and prefer one for this.

**Comment by mtb-za** [comment]
Just checked on another SWC repo (the git-novice one, since it was at the top), and it creates a fork automatically. This is a minor annoyance, but it makes sense, I guess.

**Pull request merged**
