### PR TITLE
biography for aammd

### PR DESCRIPTION
**Pull request by aammd**

### CODE REVIEW

**Comment by gvwilson** [comment]
Hi @aammd,
In order to render properly, your bio needs a short header at the top with the author's name, the publication date, the title, and a few tags. Please look in _submissions/round-12/0/2015-02-01-about-greg-wilson.md for an example, then edit your page again to include that header - the pull request will then update automatically.
Thanks,
Greg

**Comment by aammd** [comment]
Hi @gvwilson , I think this should be OK now!

**Comment by eddelbuettel** [comment]
Andrew,

Line 5 still is `+permalink: /2015/02/greg-wilson/` but I somehow doubt that is your name.

Don't we hate it when computers are so finicky?

Cheers, Dirk

**Comment by aammd** [comment]
@eddelbuettel Thank you very much. I had been wondering if there was still some outstanding problem. Now corrected.

**Pull request merged**
