### PR TITLE
Added Richard Tomsett's bio

### PR DESCRIPTION
**Pull request by richardtomsett**
Added my bio post as instructed in Greg's email

### CODE REVIEW

**Comment by bandyopa** [comment]
Hi Richard, I have a comment about your commits. In particular, could you please squash the two commits so that they become one? Your first commit has one line, whereas the second commit is the "real" one. Also, be sure to keep the commit message clear about whose biography it is. Once the PR gets merged, your commit will be one of many, and therefore will not provide sufficient information for others who look at it at a future point in time. In general, commit messages should completely specify the contents of that commit.

**Comment by richardtomsett** [comment]
Hi, thanks for the tips and apologies for the double commit! I attempted to squash the two commits together, but in doing so have apparently created two new commits. Hmm. Going to close this pull request and try again...

**Comment by msarahan** [comment]
Hi,

Squashing was something I really struggled with when I started contributing to OSS projects.  This link might help:
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

If you have questions, I'm happy to help on the mailing list or by chat (msarahan@gmail.com)

You don't need to do a new PR, but you will need to force your push to github with a line like this:
git push origin +gh-pages

where gh-pages is the branch name.

EDITED 20150206: changed gh_pages (wrong branch name) to gh-pages

**Comment by richardtomsett** [comment]
Excellent, cheers Mike. I closed the original PR and did a new one in the
end...

**Pull request closed without merging**
