### PR TITLE
Ben Weinstein

### PR DESCRIPTION
**Pull request by bw4sz**
I hope its alright that i added a 'figures' folder for knitting to .md

I'm a very visual person, so i wanted to try a clear multiple choice question that involved graphs.

Let me know if there was a better way of embedding code, i usually knit to html, but that doesn't render directly in the github browser.

### CODE REVIEW

**Comment by gvwilson** [comment]
Hi @bw4sz,
I'm all in favor of diagrams, but this adds 61 files - can you please add just-and-only the blog post and the diagram itself, not the CSS, icon files, etc.?
Thanks,
@gvwilson

**Comment by bw4sz** [comment]
Sorry greg, comments in pull requests don't get pushed to my email. I was just looking for comments on my post and can see this. Okay, let me think how i was supposed to do this correctly.

**Comment by bw4sz** [comment]
Yeah, i wonder what the best way to push R + plots code to markdown that can be viewed online. The html file does not have everything embedded. I wonder how other people are doing it. I'm just knitting to html and keeping the .md file in Rstudio. Then just deleting the html.

**Comment by hgibling** [comment]
Hi Ben,

Not trying to 'eavesdrop' on your submission, but I stumbled upon this pull request and figured I'd post. I used knittr for a Coursera course last week, so it's fresh in my mind.

Try submitting the .md file automatically generated when you knit, instead of the .Rmd file or or making a new .md file. The generated .md will have the text integrated with the plot and will be ready to post on the blog.

Adding the following to the top of your .Rmd file before you knit should generate an .md file along with the html file (but only push the .md for your pull request):

```
---
output:
  html_document:
    keep_md: true
---
```

**Comment by bw4sz** [comment]
Thanks @hgibling, i did have that set in the header. The file still exists - but the image is empty if you delete the folder.

**Comment by bw4sz** [comment]
still pretty ugly. I guess this isn't worth doing in the future. Knitr makes html so pretty, i thought it would be easy to get the .md intermediate on to github pages.

**Pull request merged**
