### PR TITLE
Adding MCQ about Git Hub Blog

### PR DESCRIPTION
**Pull request by LaurieBa**
Adding MCS about adding a second blog post to git hub

### CODE REVIEW

**Comment by gvwilson** [comment]
@LaurieBa was this file truncated accidentally?

**Comment by LaurieBa** [comment]
Hi Greg, I tried to send it again. Could there be something in how I am
writing the MCQ that would be truncating it? The other version I uploaded
appears the same. Here is the text file attached.

Cheers,

 Laurie

On Fri, Mar 13, 2015 at 4:37 AM, Greg Wilson notifications@github.com
wrote:

> @LaurieBa https://github.com/LaurieBa was this file truncated
> accidentally?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swcarpentry/training-course/pull/347#issuecomment-78795947
> .

## 

Laurie Baker
University of St. Andrews '11

**Comment by gvwilson** [comment]
Hi @LaurieBa - if you look at https://github.com/swcarpentry/training-course/pull/347/files, you'll see two files with different names, both of which have one question rather than two.  I can fix the double file problem, but should the file(s) have a second question?

**Comment by gvwilson** [comment]
Hi Laurie,
I'm sorry, but there wasn't an attached file - can you please re-send?
Thx,
G

On 2015-03-13 9:23 AM, LaurieBa wrote:

> Hi Greg, I tried to send it again. Could there be something in how I am
> writing the MCQ that would be truncating it? The other version I uploaded
> appears the same. Here is the text file attached.
> 
> Cheers,
> 
> Laurie
> 
> On Fri, Mar 13, 2015 at 4:37 AM, Greg Wilson notifications@github.com
> wrote:
> 
> > @LaurieBa https://github.com/LaurieBa was this file truncated
> > accidentally?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/swcarpentry/training-course/pull/347#issuecomment-78795947
> > .
> 
> ## 
> 
> Laurie Baker
> University of St. Andrews '11
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/training-course/pull/347#issuecomment-79097162.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Comment by LaurieBa** [comment]
Hi Greg,

Hmmm, I can see the attachment on the last e-mail from my end. Is it a
problem if it is a .md file? Here is the file as a .txt, let me know if it
attaches okay.

Sorry my post is having issues.

Laurie

On Sat, Mar 14, 2015 at 2:24 AM, Greg Wilson notifications@github.com
wrote:

> Hi Laurie,
> I'm sorry, but there wasn't an attached file - can you please re-send?
> Thx,
> G
> 
> On 2015-03-13 9:23 AM, LaurieBa wrote:
> 
> > Hi Greg, I tried to send it again. Could there be something in how I am
> > writing the MCQ that would be truncating it? The other version I uploaded
> > appears the same. Here is the text file attached.
> > 
> > Cheers,
> > 
> > Laurie
> > 
> > On Fri, Mar 13, 2015 at 4:37 AM, Greg Wilson notifications@github.com
> > wrote:
> > 
> > > @LaurieBa https://github.com/LaurieBa was this file truncated
> > > accidentally?
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> > > <
> > > https://github.com/swcarpentry/training-course/pull/347#issuecomment-78795947
> > > 
> > > .
> > 
> > ## 
> > 
> > Laurie Baker
> > University of St. Andrews '11
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/swcarpentry/training-course/pull/347#issuecomment-79097162
> > .
> 
> ## 
> 
> Dr. Greg Wilson | gvwilson@software-carpentry.org
> Software Carpentry | http://software-carpentry.org
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/swcarpentry/training-course/pull/347#issuecomment-79717575
> .

## 

Laurie Baker
University of St. Andrews '11

---

date: 2015-03-12
round: Round 12
title: Adding a second post to the github blog
author: Laurie Baker
permalink: /2015/03/laurie-baker-mcq/
tags:
- Assessment

##  - MCQ

Although this is not apart of a specific lesson, I thought it would be useful to have a question to check about the run through you do in the terminal for submitting your second blog post. 

MCQ 1. The Question:

You’ve successfully cloned the training course repository and added your first GitHub blog post. What is the correct workflow in the terminal when adding your second ever GitHub Blog post?
A.  1. git pull upstream gh-pages 2. git add 2015-02-26-for-loops-R.md 3. git commit 2015-02-26-for-loops-R.md 4. git push origin gh-pages.

B.  1. git clone https://github.com/your-repo/training-course.git 2. git remote add upstream https://github.com/swcarpentry/training-course.git 3. git add 2015-02-26-for-loops-R.md 3. git commit 2015-02-26-for-loops-R.md 4. git push origin gh-pages.

C.  1. git clone https://github.com/your-repo/training-course.git 2. git pull upstream gh-pages 3. git add 2015-02-26-for-loops-R.md 4. git commit 2015-02-26-for-loops-R.md 5. git push origin gh-pages.

D.  1. git remote add upstream https://github.com/swcarpentry/training-course.git 2. git pull upstream gh-pages 3. git add 2015-02-26-for-loops-R.md 4. git commit 2015-02-26-for-loops-R.md 5. git push origin gh-pages.

MCQ 2 The possible answers with explanations for the distractors

A.  1. git pull upstream gh-pages 2. git add 2015-02-26-for-loops-R.md 3. git commit 2015-02-26-for-loops-R.md 4. git push origin gh-pages.

In this question the learner has gotten the correct work flow apart from the fact that they need to add the upstream once for this second blog post. 

B.  1. git clone https://github.com/your-repo/training-course.git 2. git remote add upstream https://github.com/swcarpentry/training-course.git 3. git add 2015-02-26-for-loops-R.md 3. git commit 2015-02-26-for-loops-R.md 4. git push origin gh-pages.

In the question the learner will have confused that you only need to clone the training course repository on git once and that you only need to pull what is upstream to update your copy of the training course.

C.  1. git clone https://github.com/your-repo/training-course.git 2. git pull upstream gh-pages 3. git add 2015-02-26-for-loops-R.md 4. git commit 2015-02-26-for-loops-R.md 5. git push origin gh-pages.

In the question the learner will have confused that you only need to clone the training course repository on git once. They have also forgotten that as this is their second blog post, they will also need to add the upstream once per repository. 

D.  1. git remote add upstream https://github.com/swcarpentry/training-course.git 2. git pull upstream gh-pages 3. git add 2015-02-26-for-loops-R.md 4. git commit 2015-02-26-for-loops-R.md 5. git push origin gh-pages.

This is the correct work flow.

**Comment by gvwilson** [comment]
Hi Laurie,
This one's arrived - I'll merge it in.
Thx,
G

On 2015-03-15 9:27 AM, LaurieBa wrote:

> Hi Greg,
> 
> Hmmm, I can see the attachment on the last e-mail from my end. Is it a
> problem if it is a .md file? Here is the file as a .txt, let me know if it
> attaches okay.
> 
> Sorry my post is having issues.
> 
> Laurie
> 
> On Sat, Mar 14, 2015 at 2:24 AM, Greg Wilson notifications@github.com
> wrote:
> 
> > Hi Laurie,
> > I'm sorry, but there wasn't an attached file - can you please re-send?
> > Thx,
> > G
> > 
> > On 2015-03-13 9:23 AM, LaurieBa wrote:
> > 
> > > Hi Greg, I tried to send it again. Could there be something in how 
> > > I am
> > > writing the MCQ that would be truncating it? The other version I 
> > > uploaded
> > > appears the same. Here is the text file attached.
> > > 
> > > Cheers,
> > > 
> > > Laurie
> > > 
> > > On Fri, Mar 13, 2015 at 4:37 AM, Greg Wilson 
> > > notifications@github.com
> > > wrote:
> > > 
> > > > @LaurieBa https://github.com/LaurieBa was this file truncated
> > > > accidentally?
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > 
> > > > <
> > 
> > https://github.com/swcarpentry/training-course/pull/347#issuecomment-78795947
> > 
> > > > .
> > > 
> > > ## 
> > > 
> > > Laurie Baker
> > > University of St. Andrews '11
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/swcarpentry/training-course/pull/347#issuecomment-79097162
> > 
> > > .
> > 
> > ## 
> > 
> > Dr. Greg Wilson | gvwilson@software-carpentry.org
> > Software Carpentry | http://software-carpentry.org
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > 
> > https://github.com/swcarpentry/training-course/pull/347#issuecomment-79717575
> > .
> 
> ## 
> 
> Laurie Baker
> University of St. Andrews '11
> 
> ---
> 
> date: 2015-03-12
> round: Round 12
> title: Adding a second post to the github blog
> author: Laurie Baker
> permalink: /2015/03/laurie-baker-mcq/
> tags:
> - Assessment
> 
> ## \- MCQ
> 
> Although this is not apart of a specific lesson, I thought it would be 
> useful to have a question to check about the run through you do in the 
> terminal for submitting your second blog post. MCQ 1. The Question:
> You’ve successfully cloned the training course repository and added 
> your first GitHub blog post. What is the correct workflow in the 
> terminal when adding your second ever GitHub Blog post? A. 1. git pull 
> upstream gh-pages 2. git add 2015-02-26-for-loops-R.md 3. git commit 
> 2015-02-26-for-loops-R.md 4. git push origin gh-pages. B. 1. git clone 
> https://github.com/your-repo/training-course.git 2. git remote add 
> upstream https://github.com/swcarpentry/training-course.git 3. git add 
> 2015-02-26-for-loops-R.md 3. git commit 2015-02-26-for-loops-R.md 4. 
> git push origin gh-pages. C. 1. git clone 
> https://github.com/your-repo/training-course.git 2. git pull upstream 
> gh-pages 3. git add 2015-02-26-for-loops-R.md 4. git commit 
> 2015-02-26-for-loops-R.md 5. git push origin gh-pages. D. 1. git 
> remote add upstream https://github.com/swcarpentry/training-course.git 
> 2. git pull upstream gh-pages 3. git add 2015-02-26-for-loops-R.md 4. 
> git commit 2015-02-26-for-loops-R.md 5. git push origin gh-pages. MCQ 
> 2 The possible answers with explanations for the distractors
> 
> A. 1. git pull upstream gh-pages 2. git add 2015-02-26-for-loops-R.md 
> 3. git commit 2015-02-26-for-loops-R.md 4. git push origin gh-pages. 
> In this question the learner has gotten the correct work flow apart 
> from the fact that they need to add the upstream once for this second 
> blog post. B. 1. git clone 
> https://github.com/your-repo/training-course.git 2. git remote add 
> upstream https://github.com/swcarpentry/training-course.git 3. git add 
> 2015-02-26-for-loops-R.md 3. git commit 2015-02-26-for-loops-R.md 4. 
> git push origin gh-pages. In the question the learner will have 
> confused that you only need to clone the training course repository on 
> git once and that you only need to pull what is upstream to update 
> your copy of the training course. C. 1. git clone 
> https://github.com/your-repo/training-course.git 2. git pull upstream 
> gh-pages 3. git add 2015-02-26-for-loops-R.md 4. git commit 
> 2015-02-26-for-loops-R.md 5. git push origin gh-pages. In the question 
> the learner will have confused that you only need to clone the 
> training course repository on git once. They have also forgotten that 
> as this is their second blog post, they will also need to add the 
> upstream once per repository. D. 1. git remote add upstream 
> https://github.com/swcarpentry/training-course.git 2. git pull 
> upstream gh-pages 3. git add 2015-02-26-for-loops-R.md 4. git commit 
> 2015-02-26-for-loops-R.md 5. git push origin gh-pages. This is the 
> correct work flow.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/swcarpentry/training-course/pull/347#issuecomment-81095931.

## 

Dr. Greg Wilson    | gvwilson@software-carpentry.org
Software Carpentry | http://software-carpentry.org

**Pull request closed without merging**
