### PR TITLE
add a concept map for subsetting in R

### PR DESCRIPTION
**Pull request by wcornwell**

### CODE REVIEW

**Comment by gvwilson** [comment]
Hi @wcornwell,

Thanks for the PR - can you please (a) add a header of the same sort used for the biographies, and (b) include a link to the lesson this is drawn from?  The only reference to 'subset' I can find in the novice R lesson is http://swcarpentry.github.io/r-novice-inflammation/01-starting-with-data.html, and it's just mentioned in passing - is that what the concept map is for?

Thanks,
@gvwilson

**Comment by mcdickenson** [comment]
This concept map seems like it would be helpful for R learners. One improvement that you could make would be to discuss how subsetting with the `dplyr` package differs from base R.

**Comment by wcornwell** [comment]
Thanks @mcdickenson.  Good idea.

**Comment by wcornwell** [comment]
One other question this raises is when is it good to teach alternative ways of doing things, since most programming languages (and esp R) have so many very similar functions

**Comment by wcornwell** [comment]
Hey @gvwilson just wondering why this didn't get merged?  Did I mess something up?

**Comment by gvwilson** [comment]
My apologies - I didn't get the notification when you updated.  I've changed the filename to be `2015-02-22-subsetting-data-in-R.md` (our naming convention is yyyy-mm-dd-title.md), and put an exclamation mark in front of the image link `words` to embed the image.

**Pull request merged**
